version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DATABASE}"
  web:
    depends_on:
      - "db"
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      DATABASE_URL: "postgres://db:5432"
