default:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  database: <%= ENV['DATABASE_NAME'] || 'app' %>
  username: <%= ENV['DATABASE_USER'] || 'app' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'app' %>

development:
  <<: *default

production:
  <<: *default
